### ISSUE TITLE
paraview_vtk_field_extractor not working for one vertical layer

### ISSUE THREAD

**Issue by mark-petersen** [MPAS-Dev/MPAS-Tools#323]
We are dusting off the shallow water core, and tried to use paraview_vtk_field_extractor on MPAS output files where nVertLevels is 1. It can make static files, but does not make time dependent files.

**Comment by xylar** [comment]
@mark-petersen, can you point me to an example file?  I can pull out the top vertical level of a file I have but having your example might be better.

**Comment by mark-petersen** [comment]
Here are the exact commands:
```
module unload python
source /usr/projects/climate/SHARED_CLIMATE/anaconda_envs/load_latest_compass.sh
(compass_0.1.8) 
cd /lustre/scratch4/turquoise/mpeterse/runs/200710_shallow_water
paraview_vtk_field_extractor.py -v h -f output.nc -o vtk_output_sphere --xtime xtime
 -- Using progress bars --
Build time indices: 100% |########################################################################################| Time:  0:00:00

Need to define additional dimension values
Valid range for dimension nVertLevels between 0 and 0
Enter a value for dimension nVertLevels:

Extracting a total of 5 time levels.
Using file 'output.nc' as the mesh file for this extraction.

The following variables will be extracted from the input file(s).
```
If I hit enter for the nVertLevel dimension, it simply writes nothing. It should write out the variable 'h'
```
ncdump -h output.nc |grep 'h('
	double h(Time, nCells, nVertLevels) ;
ncdump -h output.nc |head|grep nVert
	nVertLevels = 1 ;
```

**Comment by mark-petersen** [comment]
If I specify nVertLevels with a -d flag, it dies.
```
paraview_vtk_field_extractor.py -v h -f output.nc -o vtk_output_sphere --xtime xtime -d nVertLevels 1
 -- Using progress bars --
Build time indices: 100% |########################################################################################| Time:  0:00:00
Traceback (most recent call last):
  File "/usr/projects/climate/SHARED_CLIMATE/anaconda_envs/base/envs/compass_0.1.8/bin/paraview_vtk_field_extractor.py", line 79, in <module>
    main()
  File "/usr/projects/climate/SHARED_CLIMATE/anaconda_envs/base/envs/compass_0.1.8/lib/python3.8/site-packages/mpas_tools/viz/paraview_extractor.py", line 420, in main
    extract_vtk(filename_pattern=args.filename_pattern,
  File "/usr/projects/climate/SHARED_CLIMATE/anaconda_envs/base/envs/compass_0.1.8/lib/python3.8/site-packages/mpas_tools/viz/paraview_extractor.py", line 260, in extract_vtk
    parse_extra_dims(dimension_list, time_series_file,
  File "/usr/projects/climate/SHARED_CLIMATE/anaconda_envs/base/envs/compass_0.1.8/lib/python3.8/site-packages/mpas_tools/viz/paraview_extractor.py", line 1032, in parse_extra_dims
    (dimName, index_string) = dim_item.split('=')
ValueError: not enough values to unpack (expected 2, got 1)
```
```
paraview_vtk_field_extractor.py -v h -f output.nc -o vtk_output_sphere --xtime xtime -d nVertLevels 0
 -- Using progress bars --
Build time indices: 100% |########################################################################################| Time:  0:00:00
Traceback (most recent call last):
  File "/usr/projects/climate/SHARED_CLIMATE/anaconda_envs/base/envs/compass_0.1.8/bin/paraview_vtk_field_extractor.py", line 79, in <module>
    main()
  File "/usr/projects/climate/SHARED_CLIMATE/anaconda_envs/base/envs/compass_0.1.8/lib/python3.8/site-packages/mpas_tools/viz/paraview_extractor.py", line 420, in main
    extract_vtk(filename_pattern=args.filename_pattern,
  File "/usr/projects/climate/SHARED_CLIMATE/anaconda_envs/base/envs/compass_0.1.8/lib/python3.8/site-packages/mpas_tools/viz/paraview_extractor.py", line 260, in extract_vtk
    parse_extra_dims(dimension_list, time_series_file,
  File "/usr/projects/climate/SHARED_CLIMATE/anaconda_envs/base/envs/compass_0.1.8/lib/python3.8/site-packages/mpas_tools/viz/paraview_extractor.py", line 1032, in parse_extra_dims
    (dimName, index_string) = dim_item.split('=')
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by xylar** [comment]
@mark-petersen, you need
```
paraview_vtk_field_extractor.py -v h -f output.nc -o vtk_output_sphere --xtime xtime -d nVertLevels=0
```
with an equals sign.

**Comment by xylar** [comment]
The only problem I'm seeing is that this is with 0000 as the start year, which python's `dateime` doesn't support.  There is no such year.

**Comment by mark-petersen** [comment]
OK. That is just set in the namelist. I'll try it again.

**Comment by mark-petersen** [comment]
Yes, when I change the namelist to
```
  6     config_start_time = '0001-01-01_00:00:00'
```
from year 0 to 1, and rerun, then everything works. The single layer was a red herring. Thanks @xylar!
